language: java

sudo: false

cache:
  directories:
    - "$HOME/.m2"

jdk:
  - openjdk8

install: true

script:
  - mvn -s .travis-maven-settings.xml clean package -B -V

# https://docs.travis-ci.com/user/deployment/pages/
# GITHUB_TOKEN is set in https://travis-ci.org/vorburger/opendaylight-simple/settings
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: target/deploy
  repo: vorburger/opendaylight-simple-binaries
  verbose: true
