language: java

sudo: false

cache:
  directories:
    - "$HOME/.m2"

jdk:
  - openjdk8

install: true

script:
  - mvn -s .travis-maven-settings.xml clean verify -B -V

# https://docs.travis-ci.com/user/deployment/pages/
# GITHUB_TOKEN is set in https://travis-ci.org/vorburger/opendaylight-simple/settings
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: target/deploy
  repo: vorburger/opendaylight-simple-binaries
  target_branch: gh-pages
